"""create login_admin table

Revision ID: 8f1c1cf3d672
Revises: 
Create Date: 2025-12-23 12:52:33.436723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f1c1cf3d672'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_admin_id'), 'login_admin', ['id'], unique=False)
    op.create_index(op.f('ix_login_admin_username'), 'login_admin', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_admin_username'), table_name='login_admin')
    op.drop_index(op.f('ix_login_admin_id'), table_name='login_admin')
    op.drop_table('login_admin')
    # ### end Alembic commands ###
